/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui;

import javax.swing.JOptionPane;
import model.Person;

/**
 *
 * @author LUCKY
 */
public class Address extends javax.swing.JPanel {

    /**
     * Creates new form Address
     */
     Person person;
    public Address(Person person) {
        initComponents();
        this.person=person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addresstitle = new javax.swing.JLabel();
        lblstreet1 = new javax.swing.JLabel();
        lblstreet2 = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        lblstate = new javax.swing.JLabel();
        lblzip = new javax.swing.JLabel();
        txtstreet1 = new javax.swing.JTextField();
        txtstreet2 = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        txtstate = new javax.swing.JTextField();
        txtzip = new javax.swing.JTextField();
        btnaddsave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        addresstitle.setBackground(new java.awt.Color(255, 255, 204));
        addresstitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addresstitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addresstitle.setText("ADDRESS INFORMATION");

        lblstreet1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblstreet1.setText("STREET ADDRESS1 :");

        lblstreet2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblstreet2.setText("STREET ADDRESS2 :");

        lblcity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblcity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcity.setText("CITY : ");

        lblstate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblstate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblstate.setText("STATE : ");

        lblzip.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblzip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblzip.setText("ZIP CODE : ");

        txtstreet1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtstreet2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtcity.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtstate.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtzip.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnaddsave.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnaddsave.setText("SAVE");
        btnaddsave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnaddsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addresstitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblstreet1)
                        .addGap(18, 18, 18)
                        .addComponent(txtstreet1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblstreet2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblcity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblstate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblzip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtstreet2)
                            .addComponent(txtcity)
                            .addComponent(txtstate)
                            .addComponent(txtzip)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnaddsave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(addresstitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstreet1)
                    .addComponent(txtstreet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstreet2)
                    .addComponent(txtstreet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcity)
                    .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstate)
                    .addComponent(txtstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblzip)
                    .addComponent(txtzip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnaddsave)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddsaveActionPerformed

        // TODO add your handling code here:
        
        person.setStreet1(txtstreet1.getText());
        person.setStreet2(txtstreet2.getText());
        person.setCity(txtcity.getText());
        person.setState(txtstate.getText());
        person.setZip(txtzip.getText());
        
        JOptionPane.showMessageDialog(this, "Person Address Saved.");
    }//GEN-LAST:event_btnaddsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresstitle;
    private javax.swing.JButton btnaddsave;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblstate;
    private javax.swing.JLabel lblstreet1;
    private javax.swing.JLabel lblstreet2;
    private javax.swing.JLabel lblzip;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtstate;
    private javax.swing.JTextField txtstreet1;
    private javax.swing.JTextField txtstreet2;
    private javax.swing.JTextField txtzip;
    // End of variables declaration//GEN-END:variables
}
