/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Person;

/**
 *
 * @author Divya Sharma
 */
public class addviewJpanel extends javax.swing.JPanel {

    /**
     * Creates new form addviewJpanel
     */
    Person person;
    public addviewJpanel(Person person) {
        initComponents();
        this.person=person;
        displayPerson();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcity = new javax.swing.JTextField();
        txtstate = new javax.swing.JTextField();
        txtzip = new javax.swing.JTextField();
        addresstitle = new javax.swing.JLabel();
        lblstreet1 = new javax.swing.JLabel();
        lblstreet2 = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        lblstate = new javax.swing.JLabel();
        lblzip = new javax.swing.JLabel();
        txtstreet1 = new javax.swing.JTextField();
        txtstreet2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtcity.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtstate.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtzip.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        addresstitle.setBackground(new java.awt.Color(255, 204, 204));
        addresstitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addresstitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addresstitle.setText("ADDRESS INFORMATION");

        lblstreet1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblstreet1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblstreet1.setText("STREET ADDRESS1 :");

        lblstreet2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblstreet2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblstreet2.setText("STREET ADDRESS2 :");

        lblcity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblcity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcity.setText("CITY : ");

        lblstate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblstate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblstate.setText("STATE : ");

        lblzip.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblzip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblzip.setText("ZIP CODE : ");

        txtstreet1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtstreet2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addresstitle, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblstreet1)
                            .addGap(18, 18, 18)
                            .addComponent(txtstreet1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblstreet2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblcity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblstate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblzip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtstreet2)
                                .addComponent(txtcity)
                                .addComponent(txtstate)
                                .addComponent(txtzip))))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(addresstitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblstreet1)
                        .addComponent(txtstreet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblstreet2)
                        .addComponent(txtstreet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblcity)
                        .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblstate)
                        .addComponent(txtstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblzip)
                        .addComponent(txtzip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(39, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresstitle;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblstate;
    private javax.swing.JLabel lblstreet1;
    private javax.swing.JLabel lblstreet2;
    private javax.swing.JLabel lblzip;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtstate;
    private javax.swing.JTextField txtstreet1;
    private javax.swing.JTextField txtstreet2;
    private javax.swing.JTextField txtzip;
    // End of variables declaration//GEN-END:variables

    private void displayPerson() {
        txtstreet1.setText(person.getStreet1());
        txtstreet2.setText(person.getStreet2());
        txtcity.setText(person.getCity());
        txtstate.setText(person.getState());
        txtzip.setText(person.getZip()); //To change body of generated methods, choose Tools | Templates.
    }
}
