/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui;

import javax.swing.JOptionPane;
import model.Person;

/**
 *
 * @author LUCKY
 */
public class CheckingAccount extends javax.swing.JPanel {

    /**
     * Creates new form CheckingAccount
     */

     Person person;
    public CheckingAccount(Person person) {
        initComponents();
        this.person=person;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlechecking = new javax.swing.JLabel();
        lblCbankname = new javax.swing.JLabel();
        lblCroutingno = new javax.swing.JLabel();
        lblCaccno = new javax.swing.JLabel();
        lblCaccbalance = new javax.swing.JLabel();
        lblCacctype = new javax.swing.JLabel();
        txtCbankname = new javax.swing.JTextField();
        txtCroutingno = new javax.swing.JTextField();
        txtCaccno = new javax.swing.JTextField();
        txtCaccbalance = new javax.swing.JTextField();
        btnsavechecking = new javax.swing.JButton();
        lblchecking = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        titlechecking.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titlechecking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlechecking.setText("CHECKING ACCOUNT");

        lblCbankname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCbankname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCbankname.setText("BANK NAME :");

        lblCroutingno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCroutingno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCroutingno.setText("ROUTING NUMBER:");

        lblCaccno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCaccno.setText("ACCOUNT NUMBER:");

        lblCaccbalance.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCaccbalance.setText("ACCOUNT BALANCE:");

        lblCacctype.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCacctype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCacctype.setText("ACCOUNT TYPE:");

        txtCbankname.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCroutingno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCaccno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCaccbalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnsavechecking.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnsavechecking.setText("SAVE");
        btnsavechecking.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsavechecking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavecheckingActionPerformed(evt);
            }
        });

        lblchecking.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblchecking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblchecking.setText("CHECKING");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlechecking, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCaccno)
                            .addComponent(lblCaccbalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblCbankname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCroutingno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblCacctype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCroutingno)
                            .addComponent(txtCaccno)
                            .addComponent(txtCaccbalance)
                            .addComponent(lblchecking, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(txtCbankname)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnsavechecking, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titlechecking)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCbankname)
                    .addComponent(txtCbankname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCroutingno)
                    .addComponent(txtCroutingno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCaccno)
                    .addComponent(txtCaccno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCaccbalance)
                    .addComponent(txtCaccbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCacctype)
                    .addComponent(lblchecking))
                .addGap(18, 18, 18)
                .addComponent(btnsavechecking)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsavecheckingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavecheckingActionPerformed

        // TODO add your handling code here:
        person.setCBankname(txtCbankname.getText());
        person.setCRoutingno(txtCroutingno.getText());
        person.setCAccno(txtCaccno.getText());
        person.setCAccbal(txtCaccbalance.getText());
        
        JOptionPane.showMessageDialog(this, "Person Checking Account Information Saved.");
        
        
    }//GEN-LAST:event_btnsavecheckingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsavechecking;
    private javax.swing.JLabel lblCaccbalance;
    private javax.swing.JLabel lblCaccno;
    private javax.swing.JLabel lblCacctype;
    private javax.swing.JLabel lblCbankname;
    private javax.swing.JLabel lblCroutingno;
    private javax.swing.JLabel lblchecking;
    private javax.swing.JLabel titlechecking;
    private javax.swing.JTextField txtCaccbalance;
    private javax.swing.JTextField txtCaccno;
    private javax.swing.JTextField txtCbankname;
    private javax.swing.JTextField txtCroutingno;
    // End of variables declaration//GEN-END:variables
}
