/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Person;

/**
 *
 * @author Divya Sharma
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    Person person;

    public MainJFrame() {
        initComponents();

        person = new Person();
//        CreatejPanel createPanel = new CreatejPanel(person);
//        DemojSplitPane.setRightComponent(createPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DemojSplitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnView = new javax.swing.JButton();
        btndemo = new javax.swing.JButton();
        btnaddress = new javax.swing.JButton();
        btnsavings = new javax.swing.JButton();
        btnchecking = new javax.swing.JButton();
        btnlicense = new javax.swing.JButton();
        btnmedical = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnviewdemo = new javax.swing.JButton();
        savview = new javax.swing.JButton();
        checkview = new javax.swing.JButton();
        addviewJpanel = new javax.swing.JButton();
        lisview = new javax.swing.JButton();
        medview = new javax.swing.JButton();
        workarea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setBackground(new java.awt.Color(93, 116, 116));

        btnView.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnView.setText("VIEW INFORMATION");
        btnView.setActionCommand("VIEW INFORMATION");
        btnView.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btndemo.setFont(new java.awt.Font("Tahoma", 3, 8)); // NOI18N
        btndemo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btndemo.setLabel("DEMOGRAPHIC");
        btndemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndemoActionPerformed(evt);
            }
        });

        btnaddress.setFont(new java.awt.Font("Tahoma", 3, 8)); // NOI18N
        btnaddress.setText("ADDRESS");
        btnaddress.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddressActionPerformed(evt);
            }
        });

        btnsavings.setFont(new java.awt.Font("Tahoma", 3, 8)); // NOI18N
        btnsavings.setText("SAVINGS");
        btnsavings.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsavings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavingsActionPerformed(evt);
            }
        });

        btnchecking.setFont(new java.awt.Font("Tahoma", 3, 8)); // NOI18N
        btnchecking.setText("CHEC KING");
        btnchecking.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnchecking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckingActionPerformed(evt);
            }
        });

        btnlicense.setFont(new java.awt.Font("Tahoma", 3, 8)); // NOI18N
        btnlicense.setText("LICENSE");
        btnlicense.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlicenseActionPerformed(evt);
            }
        });

        btnmedical.setFont(new java.awt.Font("Tahoma", 3, 8)); // NOI18N
        btnmedical.setText("MEDICAL");
        btnmedical.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnmedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmedicalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User Information");

        btnviewdemo.setFont(new java.awt.Font("Tahoma", 3, 8)); // NOI18N
        btnviewdemo.setText("VIEW");
        btnviewdemo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnviewdemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewdemoActionPerformed(evt);
            }
        });

        savview.setFont(new java.awt.Font("Tahoma", 3, 8)); // NOI18N
        savview.setText("VIEW");
        savview.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        savview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savviewActionPerformed(evt);
            }
        });

        checkview.setFont(new java.awt.Font("Tahoma", 3, 8)); // NOI18N
        checkview.setText("VIEW");
        checkview.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkviewActionPerformed(evt);
            }
        });

        addviewJpanel.setFont(new java.awt.Font("Tahoma", 3, 8)); // NOI18N
        addviewJpanel.setText("VIEW");
        addviewJpanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addviewJpanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addviewJpanelActionPerformed(evt);
            }
        });

        lisview.setFont(new java.awt.Font("Tahoma", 3, 8)); // NOI18N
        lisview.setText("VIEW");
        lisview.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lisview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lisviewActionPerformed(evt);
            }
        });

        medview.setFont(new java.awt.Font("Tahoma", 3, 8)); // NOI18N
        medview.setText("VIEW");
        medview.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        medview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(controlPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnView))
                            .addGroup(controlPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btndemo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnviewdemo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(controlPanelLayout.createSequentialGroup()
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnlicense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnchecking, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnsavings, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnmedical, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnaddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(controlPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkview, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lisview, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(medview, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(controlPanelLayout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(addviewJpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(savview, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(13, 13, 13))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndemo)
                    .addComponent(btnviewdemo))
                .addGap(18, 18, 18)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaddress)
                    .addComponent(addviewJpanel))
                .addGap(18, 18, 18)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsavings)
                    .addComponent(savview))
                .addGap(18, 18, 18)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnchecking)
                    .addComponent(checkview))
                .addGap(18, 18, 18)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlicense)
                    .addComponent(lisview))
                .addGap(18, 18, 18)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmedical)
                    .addComponent(medview))
                .addGap(65, 65, 65)
                .addComponent(btnView)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        DemojSplitPane.setLeftComponent(controlPanel);

        workarea.setBackground(new java.awt.Color(93, 116, 116));
        workarea.setForeground(new java.awt.Color(51, 16, 16));

        javax.swing.GroupLayout workareaLayout = new javax.swing.GroupLayout(workarea);
        workarea.setLayout(workareaLayout);
        workareaLayout.setHorizontalGroup(
            workareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );
        workareaLayout.setVerticalGroup(
            workareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        DemojSplitPane.setRightComponent(workarea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DemojSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DemojSplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        ViewjPanel viewPanel = new ViewjPanel(person);
        DemojSplitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btndemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndemoActionPerformed
        // TODO add your handling code here:
        CreatejPanel createPanel = new CreatejPanel(person);
        DemojSplitPane.setRightComponent(createPanel);
    }//GEN-LAST:event_btndemoActionPerformed

    private void btnaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddressActionPerformed
        Address address = new Address(person);
        DemojSplitPane.setRightComponent(address);        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddressActionPerformed

    private void btnsavingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavingsActionPerformed
        SavingAccount savingAccount = new SavingAccount(person);
        DemojSplitPane.setRightComponent(savingAccount);          // TODO add your handling code here:
    }//GEN-LAST:event_btnsavingsActionPerformed

    private void btncheckingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckingActionPerformed
        CheckingAccount checkingAccount = new CheckingAccount(person);
        DemojSplitPane.setRightComponent(checkingAccount);  // TODO add your handling code here:
    }//GEN-LAST:event_btncheckingActionPerformed

    private void btnlicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlicenseActionPerformed
        LicenceInfo licenceInfo = new LicenceInfo(person);
        DemojSplitPane.setRightComponent(licenceInfo);  // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlicenseActionPerformed

    private void btnmedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmedicalActionPerformed
        MedicalRecord medicalRecord = new MedicalRecord(person);
        DemojSplitPane.setRightComponent(medicalRecord); // TODO add your handling code here:
    }//GEN-LAST:event_btnmedicalActionPerformed

    private void btnviewdemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewdemoActionPerformed
        // TODO add your handling code here:
         demviewJPanel viewPanel = new demviewJPanel(person);
        DemojSplitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_btnviewdemoActionPerformed

    private void addviewJpanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addviewJpanelActionPerformed
        // TODO add your handling code here:
        addviewJpanel viewPanel = new addviewJpanel(person);
        DemojSplitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_addviewJpanelActionPerformed

    private void savviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savviewActionPerformed
        // TODO add your handling code here:
        viewsavingsJpanel viewPanel = new viewsavingsJpanel(person);
        DemojSplitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_savviewActionPerformed

    private void checkviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkviewActionPerformed
        // TODO add your handling code here:
        viewcheckingJpanel viewPanel = new viewcheckingJpanel(person);
        DemojSplitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_checkviewActionPerformed

    private void lisviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lisviewActionPerformed
        // TODO add your handling code here:
        viewlicenJPanel viewPanel = new viewlicenJPanel(person);
        DemojSplitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_lisviewActionPerformed

    private void medviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medviewActionPerformed
        // TODO add your handling code here:
        viewmedJPanel viewPanel = new viewmedJPanel(person);
        DemojSplitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_medviewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane DemojSplitPane;
    private javax.swing.JButton addviewJpanel;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnaddress;
    private javax.swing.JButton btnchecking;
    private javax.swing.JButton btndemo;
    private javax.swing.JButton btnlicense;
    private javax.swing.JButton btnmedical;
    private javax.swing.JButton btnsavings;
    private javax.swing.JButton btnviewdemo;
    private javax.swing.JButton checkview;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lisview;
    private javax.swing.JButton medview;
    private javax.swing.JButton savview;
    private javax.swing.JPanel workarea;
    // End of variables declaration//GEN-END:variables
}
