/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui;

import javax.swing.JOptionPane;
import model.Person;

/**
 *
 * @author LUCKY
 */
public class MedicalRecord extends javax.swing.JPanel {

    /**
     * Creates new form MedicalRecord
     */
    
      Person person;
    public MedicalRecord(Person person) {
        initComponents();
        this.person=person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlemedical = new javax.swing.JLabel();
        lblmedrecno = new javax.swing.JLabel();
        lblall1 = new javax.swing.JLabel();
        lblall2 = new javax.swing.JLabel();
        lblall3 = new javax.swing.JLabel();
        txtmedrecno = new javax.swing.JTextField();
        txtall1 = new javax.swing.JTextField();
        txtall2 = new javax.swing.JTextField();
        txtall3 = new javax.swing.JTextField();
        btnsavemedical = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        titlemedical.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titlemedical.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlemedical.setText("MEDICAL INFORMATION");

        lblmedrecno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblmedrecno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmedrecno.setText("RECORD NUMBER:");

        lblall1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblall1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblall1.setText("ALLERGY1 :");

        lblall2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblall2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblall2.setText("ALLERGY2 :");

        lblall3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblall3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblall3.setText("ALLERGY3 :");

        txtmedrecno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtall1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtall2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtall3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnsavemedical.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnsavemedical.setText("SAVE");
        btnsavemedical.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsavemedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavemedicalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlemedical, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblmedrecno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblall1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblall2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblall3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtall2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(txtall1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtall3)
                            .addComponent(txtmedrecno, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnsavemedical, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlemedical)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmedrecno)
                    .addComponent(txtmedrecno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblall1)
                    .addComponent(txtall1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblall2)
                    .addComponent(txtall2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblall3)
                    .addComponent(txtall3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnsavemedical)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsavemedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavemedicalActionPerformed
        // TODO add your handling code here:
                   
        
        person.setMedicalrecordno(txtmedrecno.getText());
        person.setAllergy1(txtall1.getText());
        person.setAllergy2(txtall2.getText());
        person.setAllergy3(txtall3.getText());
        
        JOptionPane.showMessageDialog(this, "Person License Information Saved.");
    }//GEN-LAST:event_btnsavemedicalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsavemedical;
    private javax.swing.JLabel lblall1;
    private javax.swing.JLabel lblall2;
    private javax.swing.JLabel lblall3;
    private javax.swing.JLabel lblmedrecno;
    private javax.swing.JLabel titlemedical;
    private javax.swing.JTextField txtall1;
    private javax.swing.JTextField txtall2;
    private javax.swing.JTextField txtall3;
    private javax.swing.JTextField txtmedrecno;
    // End of variables declaration//GEN-END:variables
}
