/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.Person;

/**
 *
 * @author LUCKY
 */
public class SavingAccount extends javax.swing.JPanel {

    /**
     * Creates new form SavingAccount
     */
    Person person;

    public SavingAccount(Person person) {
        initComponents();
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Savingstitle = new javax.swing.JLabel();
        lblbankname = new javax.swing.JLabel();
        lblroutingno = new javax.swing.JLabel();
        lblaccno = new javax.swing.JLabel();
        lblaccbalance = new javax.swing.JLabel();
        lblacctype = new javax.swing.JLabel();
        txtbankname = new javax.swing.JTextField();
        txtroutingno = new javax.swing.JTextField();
        txtaccno = new javax.swing.JTextField();
        txtaccbalance = new javax.swing.JTextField();
        lblsavings = new javax.swing.JLabel();
        btnsavacc = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Savingstitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Savingstitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Savingstitle.setText("SAVINGS ACCOUNT");

        lblbankname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblbankname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbankname.setText("BANK NAME :");

        lblroutingno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblroutingno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblroutingno.setText("ROUTING NUMBER:");

        lblaccno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblaccno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblaccno.setText("ACCOUNT NUMBER:");

        lblaccbalance.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblaccbalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblaccbalance.setText("ACCOUNT BALANCE:");

        lblacctype.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblacctype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblacctype.setText("ACCOUNT TYPE :");

        txtbankname.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtroutingno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtaccno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtaccbalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblsavings.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblsavings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsavings.setText("SAVINGS");

        btnsavacc.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnsavacc.setText("SAVE");
        btnsavacc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsavacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavaccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Savingstitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblaccno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblroutingno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblaccbalance, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(lblacctype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblbankname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbankname)
                            .addComponent(txtroutingno)
                            .addComponent(txtaccno)
                            .addComponent(txtaccbalance)
                            .addComponent(lblsavings, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsavacc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Savingstitle)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbankname)
                    .addComponent(txtbankname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblroutingno)
                    .addComponent(txtroutingno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblaccno)
                    .addComponent(txtaccno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblaccbalance)
                    .addComponent(txtaccbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblacctype)
                    .addComponent(lblsavings))
                .addGap(18, 18, 18)
                .addComponent(btnsavacc)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsavaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavaccActionPerformed
        // TODO add your handling code here:
        
                   person.setSBankname(txtbankname.getText());
                  person.setSRoutingno(txtroutingno.getText());
                  person.setSAccno(txtaccno.getText());
                  person.setSAccbal(txtaccbalance.getText());
                   
                   JOptionPane.showMessageDialog(this, "Person Savings Account Information Saved.");
    }//GEN-LAST:event_btnsavaccActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Savingstitle;
    private javax.swing.JButton btnsavacc;
    private javax.swing.JLabel lblaccbalance;
    private javax.swing.JLabel lblaccno;
    private javax.swing.JLabel lblacctype;
    private javax.swing.JLabel lblbankname;
    private javax.swing.JLabel lblroutingno;
    private javax.swing.JLabel lblsavings;
    private javax.swing.JTextField txtaccbalance;
    private javax.swing.JTextField txtaccno;
    private javax.swing.JTextField txtbankname;
    private javax.swing.JTextField txtroutingno;
    // End of variables declaration//GEN-END:variables
}
