/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


import java.awt.Image;
import javax.swing.ImageIcon;
import model.Person;

/**
 *
 * @author Divya Sharma
 */
public class ViewjPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewjPanel
     */
    Person person;
    
    public ViewjPanel(Person person) {
        initComponents();
        this.person=person;
        displayPerson();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblstate = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        txtstreet2 = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        lblstreet2 = new javax.swing.JLabel();
        txtstreet1 = new javax.swing.JTextField();
        lblstreet1 = new javax.swing.JLabel();
        addresstitle = new javax.swing.JLabel();
        lblzip = new javax.swing.JLabel();
        txtzip = new javax.swing.JTextField();
        txtstate = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtDOB = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblLname = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblFname = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        lblheight = new javax.swing.JLabel();
        txtheight = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        lblweight = new javax.swing.JLabel();
        txtweight = new javax.swing.JTextField();
        lblage = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblacctype = new javax.swing.JLabel();
        txtroutingno = new javax.swing.JTextField();
        txtaccbalance = new javax.swing.JTextField();
        lblaccbalance = new javax.swing.JLabel();
        Savingstitle = new javax.swing.JLabel();
        txtaccno = new javax.swing.JTextField();
        lblsavings = new javax.swing.JLabel();
        lblroutingno = new javax.swing.JLabel();
        lblaccno = new javax.swing.JLabel();
        txtbankname = new javax.swing.JTextField();
        lblbankname = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtmedrecno = new javax.swing.JTextField();
        lblall1 = new javax.swing.JLabel();
        txtall2 = new javax.swing.JTextField();
        lblall2 = new javax.swing.JLabel();
        lblall3 = new javax.swing.JLabel();
        titlemedical = new javax.swing.JLabel();
        txtall1 = new javax.swing.JTextField();
        txtall3 = new javax.swing.JTextField();
        lblmedrecno = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtissuedate = new javax.swing.JTextField();
        titlelicense = new javax.swing.JLabel();
        lblbloodgroup = new javax.swing.JLabel();
        lblphoto = new javax.swing.JLabel();
        txtlicenseno = new javax.swing.JTextField();
        lbllicenseno = new javax.swing.JLabel();
        lblexpirydate = new javax.swing.JLabel();
        txtexpirydate = new javax.swing.JTextField();
        txtbloodgroup = new javax.swing.JTextField();
        lblissuedate = new javax.swing.JLabel();
        imageContainer = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtCroutingno = new javax.swing.JTextField();
        lblCacctype = new javax.swing.JLabel();
        lblchecking = new javax.swing.JLabel();
        lblCaccbalance = new javax.swing.JLabel();
        lblCroutingno = new javax.swing.JLabel();
        lblCaccno = new javax.swing.JLabel();
        lblCbankname = new javax.swing.JLabel();
        txtCaccno = new javax.swing.JTextField();
        txtCbankname = new javax.swing.JTextField();
        txtCaccbalance = new javax.swing.JTextField();
        titlechecking = new javax.swing.JLabel();

        setBackground(new java.awt.Color(93, 116, 116));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblstate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblstate.setText("STATE : ");

        lblcity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblcity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcity.setText("CITY : ");

        txtstreet2.setEditable(false);
        txtstreet2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtcity.setEditable(false);

        lblstreet2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblstreet2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblstreet2.setText("STREET ADDRESS2 :");

        txtstreet1.setEditable(false);
        txtstreet1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblstreet1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblstreet1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblstreet1.setText("STREET ADDRESS1 :");

        addresstitle.setBackground(new java.awt.Color(255, 204, 204));
        addresstitle.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        addresstitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addresstitle.setText("ADDRESS INFORMATION");

        lblzip.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblzip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblzip.setText("ZIP CODE : ");

        txtzip.setEditable(false);
        txtzip.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtstate.setEditable(false);
        txtstate.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addresstitle, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblstreet2)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblcity)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblzip))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(txtstreet2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(lblstate)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtstate))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtzip, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblstreet1)
                            .addGap(32, 32, 32)
                            .addComponent(txtstreet1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(addresstitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstreet1)
                    .addComponent(txtstreet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstreet2)
                    .addComponent(txtstreet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcity)
                    .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblstate)
                    .addComponent(txtstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtzip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblzip))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setForeground(new java.awt.Color(93, 116, 116));

        txtDOB.setEditable(false);
        txtDOB.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblTitle.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("DEMOGRAPHIC INFORMATION");

        lblLname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLname.setText("FIRST NAME");

        lblPhone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhone.setText("PHONE NO.");

        lblSSN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSSN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSSN.setText("SSN");

        lblFname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFname.setText("LAST NAME");

        txtPhone.setEditable(false);
        txtPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtage.setEditable(false);
        txtage.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtSSN.setEditable(false);
        txtSSN.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblheight.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblheight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblheight.setText("HEIGHT");

        txtheight.setEditable(false);
        txtheight.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblDOB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDOB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDOB.setText("DOB");

        lblweight.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblweight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblweight.setText("WEIGHT");

        txtweight.setEditable(false);
        txtweight.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblage.setText("AGE");

        txtLname.setEditable(false);
        txtLname.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtFname.setEditable(false);
        txtFname.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDOB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblweight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblheight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFname, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(txtLname)
                            .addComponent(txtPhone)
                            .addComponent(txtage)
                            .addComponent(txtheight)
                            .addComponent(txtweight)
                            .addComponent(txtSSN)
                            .addComponent(txtDOB))))
                .addGap(51, 51, 51))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLname)
                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFname)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOB)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblage)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblheight)
                    .addComponent(txtheight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblweight)
                    .addComponent(txtweight))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSSN))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblacctype.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblacctype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblacctype.setText("ACCOUNT TYPE :");

        txtroutingno.setEditable(false);
        txtroutingno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtaccbalance.setEditable(false);
        txtaccbalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtaccbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaccbalanceActionPerformed(evt);
            }
        });

        lblaccbalance.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblaccbalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblaccbalance.setText("ACCOUNT BALANCE:");

        Savingstitle.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Savingstitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Savingstitle.setText("SAVINGS ACCOUNT");

        txtaccno.setEditable(false);
        txtaccno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblsavings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsavings.setText("SAVINGS");

        lblroutingno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblroutingno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblroutingno.setText("ROUTING NUMBER:");

        lblaccno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblaccno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblaccno.setText("ACCOUNT NUMBER:");

        txtbankname.setEditable(false);
        txtbankname.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblbankname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblbankname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbankname.setText("BANK NAME :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Savingstitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblaccno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblroutingno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblaccbalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblacctype, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblbankname, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbankname, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtaccbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblsavings, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtaccno, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtroutingno, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 61, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Savingstitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbankname)
                    .addComponent(txtbankname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblroutingno)
                    .addComponent(txtroutingno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblaccno)
                    .addComponent(txtaccno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblaccbalance)
                    .addComponent(txtaccbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblacctype)
                    .addComponent(lblsavings))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtmedrecno.setEditable(false);
        txtmedrecno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblall1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblall1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblall1.setText("ALLERGY1 :");

        txtall2.setEditable(false);
        txtall2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblall2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblall2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblall2.setText("ALLERGY2 :");

        lblall3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblall3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblall3.setText("ALLERGY3 :");

        titlemedical.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        titlemedical.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlemedical.setText("MEDICAL INFORMATION");

        txtall1.setEditable(false);
        txtall1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtall3.setEditable(false);
        txtall3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblmedrecno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblmedrecno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmedrecno.setText("RECORD NUMBER:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlemedical, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblmedrecno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblall1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblall2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblall3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmedrecno)
                            .addComponent(txtall1)
                            .addComponent(txtall2)
                            .addComponent(txtall3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlemedical)
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmedrecno)
                    .addComponent(txtmedrecno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblall1)
                    .addComponent(txtall1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblall2)
                    .addComponent(txtall2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblall3)
                    .addComponent(txtall3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtissuedate.setEditable(false);
        txtissuedate.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        titlelicense.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        titlelicense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlelicense.setText("LICENSE INFORMATION");

        lblbloodgroup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblbloodgroup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbloodgroup.setText("BLOOD GROUP :");

        lblphoto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblphoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblphoto.setText("PHOTO :");

        txtlicenseno.setEditable(false);
        txtlicenseno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbllicenseno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbllicenseno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllicenseno.setText("LICENSE NUMBER");

        lblexpirydate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblexpirydate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblexpirydate.setText("EXPIRY DATE :");

        txtexpirydate.setEditable(false);
        txtexpirydate.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtbloodgroup.setEditable(false);
        txtbloodgroup.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblissuedate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblissuedate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblissuedate.setText("ISSUE DATE :");

        imageContainer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlelicense, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbllicenseno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblissuedate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblexpirydate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblbloodgroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblphoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtlicenseno)
                            .addComponent(txtissuedate)
                            .addComponent(txtexpirydate)
                            .addComponent(txtbloodgroup, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(imageContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlelicense)
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllicenseno)
                    .addComponent(txtlicenseno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblissuedate)
                    .addComponent(txtissuedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblexpirydate)
                    .addComponent(txtexpirydate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbloodgroup)
                    .addComponent(txtbloodgroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblphoto))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(imageContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtCroutingno.setEditable(false);
        txtCroutingno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblCacctype.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCacctype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCacctype.setText("ACCOUNT TYPE:");

        lblchecking.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblchecking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblchecking.setText("CHECKING");

        lblCaccbalance.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCaccbalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCaccbalance.setText("ACCOUNT BALANCE:");

        lblCroutingno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCroutingno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCroutingno.setText("ROUTING NUMBER:");

        lblCaccno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCaccno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCaccno.setText("ACCOUNT NUMBER:");

        lblCbankname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCbankname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCbankname.setText("BANK NAME :");

        txtCaccno.setEditable(false);
        txtCaccno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCbankname.setEditable(false);
        txtCbankname.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCaccbalance.setEditable(false);
        txtCaccbalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        titlechecking.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        titlechecking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlechecking.setText("CHECHKING ACCOUNT");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlechecking, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCaccbalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCbankname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCroutingno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCacctype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCaccno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCbankname)
                            .addComponent(txtCroutingno)
                            .addComponent(txtCaccno)
                            .addComponent(txtCaccbalance)
                            .addComponent(lblchecking, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titlechecking)
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCbankname)
                    .addComponent(txtCbankname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCroutingno)
                    .addComponent(txtCroutingno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCaccno)
                    .addComponent(txtCaccno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCaccbalance)
                    .addComponent(txtCaccbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCacctype)
                    .addComponent(lblchecking))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtaccbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaccbalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccbalanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Savingstitle;
    private javax.swing.JLabel addresstitle;
    private javax.swing.JLabel imageContainer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblCaccbalance;
    private javax.swing.JLabel lblCaccno;
    private javax.swing.JLabel lblCacctype;
    private javax.swing.JLabel lblCbankname;
    private javax.swing.JLabel lblCroutingno;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblFname;
    private javax.swing.JLabel lblLname;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblaccbalance;
    private javax.swing.JLabel lblaccno;
    private javax.swing.JLabel lblacctype;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblall1;
    private javax.swing.JLabel lblall2;
    private javax.swing.JLabel lblall3;
    private javax.swing.JLabel lblbankname;
    private javax.swing.JLabel lblbloodgroup;
    private javax.swing.JLabel lblchecking;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblexpirydate;
    private javax.swing.JLabel lblheight;
    private javax.swing.JLabel lblissuedate;
    private javax.swing.JLabel lbllicenseno;
    private javax.swing.JLabel lblmedrecno;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JLabel lblroutingno;
    private javax.swing.JLabel lblsavings;
    private javax.swing.JLabel lblstate;
    private javax.swing.JLabel lblstreet1;
    private javax.swing.JLabel lblstreet2;
    private javax.swing.JLabel lblweight;
    private javax.swing.JLabel lblzip;
    private javax.swing.JLabel titlechecking;
    private javax.swing.JLabel titlelicense;
    private javax.swing.JLabel titlemedical;
    private javax.swing.JTextField txtCaccbalance;
    private javax.swing.JTextField txtCaccno;
    private javax.swing.JTextField txtCbankname;
    private javax.swing.JTextField txtCroutingno;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtaccbalance;
    private javax.swing.JTextField txtaccno;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtall1;
    private javax.swing.JTextField txtall2;
    private javax.swing.JTextField txtall3;
    private javax.swing.JTextField txtbankname;
    private javax.swing.JTextField txtbloodgroup;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtexpirydate;
    private javax.swing.JTextField txtheight;
    private javax.swing.JTextField txtissuedate;
    private javax.swing.JTextField txtlicenseno;
    private javax.swing.JTextField txtmedrecno;
    private javax.swing.JTextField txtroutingno;
    private javax.swing.JTextField txtstate;
    private javax.swing.JTextField txtstreet1;
    private javax.swing.JTextField txtstreet2;
    private javax.swing.JTextField txtweight;
    private javax.swing.JTextField txtzip;
    // End of variables declaration//GEN-END:variables

    private void displayPerson() {
        
        txtLname.setText(person.getLastName());
        txtFname.setText(person.getFirstName());
        txtPhone.setText(person.getPhone());
        txtDOB.setText(person.getDOB());
        txtage.setText(person.getAge());
        txtheight.setText(person.getHeight());
        txtweight.setText(person.getWeight());
        txtSSN.setText(person.getSSN());
        txtstreet1.setText(person.getStreet1());
        txtstreet2.setText(person.getStreet2());
        txtcity.setText(person.getCity());
        txtstate.setText(person.getState());
        txtzip.setText(person.getZip());
        txtbankname.setText(person.getSBankname());
        txtroutingno.setText(person.getSRoutingno());
        txtaccno.setText(person.getSAccno());
        txtaccbalance.setText(person.getSAccbal());
        txtmedrecno.setText(person.getMedicalrecordno());
        txtall1.setText(person.getAllergy1());
        txtall2.setText(person.getAllergy2());
        txtall3.setText(person.getAllergy3());
        txtlicenseno.setText(person.getLicenseno());
        txtissuedate.setText(person.getIssuedate());
        txtexpirydate.setText(person.getExpirydate());
        txtbloodgroup.setText(person.getBloodgroup());
        txtCbankname.setText(person.getCBankname());
        txtCroutingno.setText(person.getCRoutingno());
        txtCaccbalance.setText(person.getCAccbal());
        txtCaccno.setText(person.getCAccno());
        ImageIcon ii = new ImageIcon(person.getImagePath());
        Image iii = ii.getImage();
        Image newicon = iii.getScaledInstance(200, 200, Image.SCALE_SMOOTH); 
        ImageIcon icon = new ImageIcon(newicon);
        imageContainer.setIcon(icon);
    }
}
