/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Person;

/**
 *
 * @author Divya Sharma
 */
public class viewcheckingJpanel extends javax.swing.JPanel {

    /**
     * Creates new form viewcheckingJpanel
     */
    Person person;
    public viewcheckingJpanel(Person person) {
        initComponents();
        this.person=person;
        displayPerson();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCbankname = new javax.swing.JTextField();
        txtCroutingno = new javax.swing.JTextField();
        txtCaccno = new javax.swing.JTextField();
        txtCaccbalance = new javax.swing.JTextField();
        titlechecking = new javax.swing.JLabel();
        lblchecking = new javax.swing.JLabel();
        lblCbankname = new javax.swing.JLabel();
        lblCroutingno = new javax.swing.JLabel();
        lblCaccno = new javax.swing.JLabel();
        lblCaccbalance = new javax.swing.JLabel();
        lblCacctype = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtCbankname.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCroutingno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCaccno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCaccbalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        titlechecking.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titlechecking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlechecking.setText("CHECKING ACCOUNT");

        lblchecking.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblchecking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblchecking.setText("CHECKING");

        lblCbankname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCbankname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCbankname.setText("BANK NAME :");

        lblCroutingno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCroutingno.setText("ROUTING NUMBER:");

        lblCaccno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCaccno.setText("ACCOUNT NUMBER:");

        lblCaccbalance.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCaccbalance.setText("ACCOUNT BALANCE:");

        lblCacctype.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCacctype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCacctype.setText("ACCOUNT TYPE:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlechecking, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblCaccno)
                        .addComponent(lblCaccbalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCbankname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCroutingno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(lblCacctype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(75, 75, 75)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCroutingno)
                        .addComponent(txtCaccno)
                        .addComponent(txtCaccbalance)
                        .addComponent(lblchecking, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addComponent(txtCbankname))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(titlechecking)
                .addContainerGap(255, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCbankname)
                        .addComponent(txtCbankname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCroutingno)
                        .addComponent(txtCroutingno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCaccno)
                        .addComponent(txtCaccno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCaccbalance)
                        .addComponent(txtCaccbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCacctype)
                        .addComponent(lblchecking))
                    .addContainerGap(46, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCaccbalance;
    private javax.swing.JLabel lblCaccno;
    private javax.swing.JLabel lblCacctype;
    private javax.swing.JLabel lblCbankname;
    private javax.swing.JLabel lblCroutingno;
    private javax.swing.JLabel lblchecking;
    private javax.swing.JLabel titlechecking;
    private javax.swing.JTextField txtCaccbalance;
    private javax.swing.JTextField txtCaccno;
    private javax.swing.JTextField txtCbankname;
    private javax.swing.JTextField txtCroutingno;
    // End of variables declaration//GEN-END:variables

    private void displayPerson() {

    
    txtCbankname.setText(person.getCBankname());
        txtCroutingno.setText(person.getCRoutingno());
        txtCaccbalance.setText(person.getCAccbal());
    txtCaccno.setText(person.getCAccno());}
}
