/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import javax.swing.ImageIcon;
import model.Person;

/**
 *
 * @author Divya Sharma
 */
public class viewlicenJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewlicenJPanel
     */
    Person person;
    public viewlicenJPanel(Person person) {
        initComponents();
        this.person=person;
        displayPerson();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlelicense = new javax.swing.JLabel();
        lbllicenseno = new javax.swing.JLabel();
        lblissuedate = new javax.swing.JLabel();
        lblexpirydate = new javax.swing.JLabel();
        lblbloodgroup = new javax.swing.JLabel();
        lblphoto = new javax.swing.JLabel();
        txtlicenseno = new javax.swing.JTextField();
        txtissuedate = new javax.swing.JTextField();
        txtexpirydate = new javax.swing.JTextField();
        txtbloodgroup = new javax.swing.JTextField();
        imageContainer = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        titlelicense.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titlelicense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlelicense.setText("LICENSE INFORMATION");

        lbllicenseno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbllicenseno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllicenseno.setText("LICENSE NUMBER");

        lblissuedate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblissuedate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblissuedate.setText("ISSUE DATE :");

        lblexpirydate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblexpirydate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblexpirydate.setText("EXPIRY DATE :");

        lblbloodgroup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblbloodgroup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbloodgroup.setText("BLOOD GROUP :");

        lblphoto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblphoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblphoto.setText("PHOTO :");

        txtlicenseno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtissuedate.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtexpirydate.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtbloodgroup.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        imageContainer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlelicense, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbllicenseno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblissuedate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblexpirydate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblbloodgroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblphoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imageContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(86, 86, 86))
                            .addComponent(txtlicenseno)
                            .addComponent(txtissuedate)
                            .addComponent(txtexpirydate)
                            .addComponent(txtbloodgroup))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlelicense)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllicenseno)
                    .addComponent(txtlicenseno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblissuedate)
                    .addComponent(txtissuedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblexpirydate)
                    .addComponent(txtexpirydate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbloodgroup)
                    .addComponent(txtbloodgroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblphoto)
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageContainer;
    private javax.swing.JLabel lblbloodgroup;
    private javax.swing.JLabel lblexpirydate;
    private javax.swing.JLabel lblissuedate;
    private javax.swing.JLabel lbllicenseno;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JLabel titlelicense;
    private javax.swing.JTextField txtbloodgroup;
    private javax.swing.JTextField txtexpirydate;
    private javax.swing.JTextField txtissuedate;
    private javax.swing.JTextField txtlicenseno;
    // End of variables declaration//GEN-END:variables

    private void displayPerson() {
        
         txtlicenseno.setText(person.getLicenseno());
        txtissuedate.setText(person.getIssuedate());
        txtexpirydate.setText(person.getExpirydate());
        txtbloodgroup.setText(person.getBloodgroup());
        ImageIcon ii = new ImageIcon(person.getImagePath());
        Image iii = ii.getImage();
        Image newicon = iii.getScaledInstance(200, 200, Image.SCALE_SMOOTH); 
        ImageIcon icon = new ImageIcon(newicon);
        imageContainer.setIcon(icon);
        
    }
}
