/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Person;

/**
 *
 * @author Divya Sharma
 */
public class viewmedJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewmedJPanel
     */
    Person person;
    public viewmedJPanel(Person person) {
        initComponents();
        this.person=person;
        displayPerson();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlemedical = new javax.swing.JLabel();
        lblmedrecno = new javax.swing.JLabel();
        lblall1 = new javax.swing.JLabel();
        lblall2 = new javax.swing.JLabel();
        lblall3 = new javax.swing.JLabel();
        txtmedrecno = new javax.swing.JTextField();
        txtall1 = new javax.swing.JTextField();
        txtall2 = new javax.swing.JTextField();
        txtall3 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        titlemedical.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titlemedical.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlemedical.setText("MEDICAL INFORMATION");

        lblmedrecno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblmedrecno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmedrecno.setText("RECORD NUMBER:");

        lblall1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblall1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblall1.setText("ALLERGY1 :");

        lblall2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblall2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblall2.setText("ALLERGY2 :");

        lblall3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblall3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblall3.setText("ALLERGY3 :");

        txtmedrecno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtall1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtall2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtall3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(titlemedical, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblmedrecno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblall1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblall2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblall3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtall2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                .addComponent(txtall1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtall3)
                                .addComponent(txtmedrecno, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGap(7, 7, 7)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(titlemedical)
                    .addGap(37, 37, 37)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblmedrecno)
                        .addComponent(txtmedrecno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblall1)
                        .addComponent(txtall1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblall2)
                        .addComponent(txtall2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblall3)
                        .addComponent(txtall3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(54, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblall1;
    private javax.swing.JLabel lblall2;
    private javax.swing.JLabel lblall3;
    private javax.swing.JLabel lblmedrecno;
    private javax.swing.JLabel titlemedical;
    private javax.swing.JTextField txtall1;
    private javax.swing.JTextField txtall2;
    private javax.swing.JTextField txtall3;
    private javax.swing.JTextField txtmedrecno;
    // End of variables declaration//GEN-END:variables

    private void displayPerson() {
        
        txtmedrecno.setText(person.getMedicalrecordno());
        txtall1.setText(person.getAllergy1());
        txtall2.setText(person.getAllergy2());
        txtall3.setText(person.getAllergy3());
        
    }
}
